### PR TITLE
feat: add glue client wrapper

### PR DESCRIPTION
**Pull request by tvincent2**

### CODE REVIEW

**Comment by nicolas-raymond** [comment]
Why adding a dependency without using it inside the aws-lib ?

**Comment by tvincent2** [comment]
> Why adding a dependency without using it inside the aws-lib ?

Good question!
For now, we're only re-exposing `aws-sdk-glue` so we can use it in https://github.com/pbstck/aggregation-processings/pull/497.
Our intent was first to use AWS SDK instead of Rusoto, then see what is relevant for `aws-lib` and what should stay in `aggregation-processings`. For now we've only done step 1, so our PRs are still drafts.

But even if we didn't add a wrapper for the Glue client, I would argue this addition is still relevant. So many libraries follow the changes of the AWS SDK:

- the `aws-sdk-*` crates themselves
- all the other `aws-*` crates, such as `aws-types`, `aws-config`, etc.
- some other crates with AWS-related features, like `serde-dynamo` and its `aws-sdk-dynamodb+<SDK_VERSION>` feature

Discrepancies in version numbers can lead to strange errors because of incompatible types (AWS is not afraid of introducing breaking changes).
Because of that, `aws-lib` can be a convenient way to update all versions at once.

Sorry for the long answer!

**Review by erwanncloarec — APPROVED** [review]

**Review by sdeluce — APPROVED** [review]

**Review by ildede — APPROVED** [review]

**Review by cforycki — APPROVED** [review]

**Review by vmaerten — APPROVED** [review]

**Comment by cforycki** [comment]
This PR now has the glue client wrapper and not only the re-export of the sdk

**Review by lestrade-pbstck — APPROVED** [review]

**Review by ildede — APPROVED** [review]

**Review by vmaerten — APPROVED** [review]
Nice !

**Review by erwanncloarec — APPROVED** [review]

**Review by sdeluce — APPROVED** [review]
👌

**Pull request merged**
