### PR TITLE
ci(lint): add lint pr title action

### PR DESCRIPTION
**Pull request by vmaerten**

### CODE REVIEW

**Comment by vmaerten** [comment]
@erwanncloarec can you tell us what cargo-hack does and why is it needed?
It seems to fail in Rust 1.59

**Comment by vmaerten** [comment]
I'll remove it for now because it does not compile right now

**Comment by erwanncloarec** [comment]
IMO it's not a reason to remove it.
I looked and found that the last version is compatible with rust 1.60+

Do we want to keep rust 1.59 ? If yes we can just install cargo-hack with the version [0.5.21](https://github.com/taiki-e/cargo-hack/releases/tag/v0.5.21)

**Comment by erwanncloarec** [comment]
Made a PR to fix that: 
* https://github.com/pbstck/aws-lib/pull/25

**Pull request merged**
